### ISSUE TITLE
Windows is support?

### ISSUE THREAD

**Issue by oceancoll** [shodanshok/blocksync#4]
hello，i want to use this tool for vm migration. vm os is Windows. Can it support for Windows? Besides, this tool params is support bwlimit and Incremental sync? thanks~

**Comment by shodanshok** [comment]
Hi, yes, you can use it for VM migration independently of the guest OS, so in this sense Windows is supported because you can migrate a Windows guest. However it does not run on Windows as host OS or, at very least, I never tried it on Python for Windows.

Multiple `blocksync` invocations will only copy changed blocks, but they need to read *all* source/dest blocks, so they are not "true" incremental sync.

**Comment by oceancoll** [comment]
thanks for your reply. i will try it in windows later. And also, is rate limit be support, like bwlimit in rsync.

**Comment by shodanshok** [comment]
Hi, no, bwlimit is not supported at the moment.

**Comment by oceancoll** [comment]
thanks a lot~👍
